// AUTOGENERATED from tokens.json. Regenerate: npm run tokens:dist
export const tokens = {
  "colors": {
    "neutral": {
      "default": "#ffffff",
      "onDefault": "#000000",
      "accent": "#0059ff",
      "muted": "#adadad"
    }
  },
  "spacing": {
    "xs": "6px",
    "sm": "8px",
    "md": "20px"
  },
  "fontFamilies": {
    "neue-haas-unica-w1g": "\"Neue Haas Unica W1G\""
  },
  "lineHeights": {
    "0": "18px",
    "1": "24px",
    "2": "48px"
  },
  "fontWeights": {
    "neue-haas-unica-w1g-0": "400"
  },
  "fontSize": {
    "0": "14px",
    "1": "20px",
    "2": "46px"
  },
  "letterSpacing": {
    "0": "-0.05em",
    "1": "-0.01em",
    "2": "0.01em"
  },
  "paragraphSpacing": {
    "0": "0px"
  },
  "textCase": {
    "none": "none"
  },
  "textDecoration": {
    "none": "none"
  },
  "paragraphIndent": {
    "0": "0px"
  },
  "radius": {
    "sm": "4px",
    "md": "8px"
  },
  "drop-shadow": {
    "sm": "0px 4px 4px 0px #adadad"
  },
  "typography": {
    "Display": {
      "fontFamily": "\"Neue Haas Unica W1G\"",
      "fontWeight": "400",
      "fontSize": "46px",
      "lineHeight": "48px",
      "letterSpacing": "-0.05em"
    },
    "Heading": {
      "fontFamily": "\"Neue Haas Unica W1G\"",
      "fontWeight": "400",
      "fontSize": "20px",
      "lineHeight": "24px",
      "letterSpacing": "-0.01em"
    },
    "Body": {
      "fontFamily": "\"Neue Haas Unica W1G\"",
      "fontWeight": "400",
      "fontSize": "14px",
      "lineHeight": "18px",
      "letterSpacing": "0.01em"
    }
  }
};

export default tokens;
