// AUTOGENERATED from tokens.json. Regenerate: npm run tokens:dist
export const tokens = {
  "colors": {
    "neutral": {
      "default": "#ffffff",
      "onDefault": "#000000",
      "accent": "#0059ff",
      "muted": "#adadad"
    }
  },
  "spacing": {
    "md": "20px",
    "sm": "6px"
  },
  "fontFamilies": {
    "neue-haas-unica-w1g": "\"Neue Haas Unica W1G\""
  },
  "lineHeights": {
    "0": "84px",
    "1": "55px",
    "2": "normal"
  },
  "fontWeights": {
    "neue-haas-unica-w1g-0": "400"
  },
  "fontSize": {
    "0": "20px",
    "1": "55px",
    "2": "84px"
  },
  "letterSpacing": {
    "0": "-0.05em",
    "1": "-0.01em",
    "2": "0.01em"
  },
  "paragraphSpacing": {
    "0": "0px"
  },
  "textCase": {
    "none": "none"
  },
  "textDecoration": {
    "none": "none"
  },
  "paragraphIndent": {
    "0": "0px"
  },
  "typography": {
    "Display": {
      "fontWeight": "400",
      "fontSize": "84px",
      "lineHeight": "84px",
      "fontFamily": "\"Neue Haas Unica W1G\""
    },
    "Headline": {
      "fontFamily": "\"Neue Haas Unica W1G\"",
      "fontWeight": "400",
      "fontSize": "55px",
      "lineHeight": "55px"
    },
    "Body": {
      "fontFamily": "\"Neue Haas Unica W1G\"",
      "fontWeight": "400",
      "fontSize": "20px",
      "lineHeight": "normal"
    }
  }
};

export default tokens;
